//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: schema

package fbs

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for Data service
type DataClient interface{
  Record(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Record, error)  
}

type dataClient struct {
  cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
  return &dataClient{cc}
}

func (c *dataClient) Record(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Record, error) {
  out := new(Record)
  err := grpc.Invoke(ctx, "/fbs.Data/Record", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Data service
type DataServer interface {
  Record(context.Context, *Record) (*flatbuffers.Builder, error)  
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
  s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_Record_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Record)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(DataServer).Record(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/fbs.Data/Record",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(DataServer).Record(ctx, req.(* Record))
  }
  return interceptor(ctx, in, info, handler)
}


var _Data_serviceDesc = grpc.ServiceDesc{
  ServiceName: "fbs.Data",
  HandlerType: (*DataServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Record",
      Handler: _Data_Record_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

